// This file contains the mapping of link names to their expected visible selectors for assertion.
// You can expand or adjust this mapping as needed for new links or requirements.

export const linkVisibilityMap: Record<string, { selectorType: 'role' | 'locator', selector: any }> = {
  'kings_world_welcome_pack': { selectorType: 'role', selector: { role: 'button', name: 'Sign In', exact: true } },
  'kings_world_welcome_pack_mindep20': { selectorType: 'role', selector: { role: 'button', name: 'Sign In', exact: true } },
  'boosta': { selectorType: 'role', selector: { role: 'button', name: 'Sign In', exact: true } },
  'casinosanalyzer_50': { selectorType: 'role', selector: { role: 'button', name: 'Sign In', exact: true } },
  'casinosanalyzer_10': { selectorType: 'role', selector: { role: 'button', name: 'Sign In', exact: true } },
  'casinosanalyzer_20': { selectorType: 'role', selector: { role: 'button', name: 'Sign In', exact: true } },
  'casinosanalyzer_100': { selectorType: 'role', selector: { role: 'button', name: 'Sign In', exact: true } },
  'casinosanalyzer_150': { selectorType: 'role', selector: { role: 'button', name: 'Sign In', exact: true } },
  'casinosanalyzer_200': { selectorType: 'role', selector: { role: 'button', name: 'Sign In', exact: true } },
  'kings_welcome_pack': { selectorType: 'role', selector: { role: 'button', name: 'GET IT NOW', exact: false, first: true } },
  'kings_welcome_pack_mindep20': { selectorType: 'role', selector: { role: 'button', name: 'GET IT NOW', exact: false, first: true } },
  'kings_welcome_pack_mindep30': { selectorType: 'role', selector: { role: 'button', name: 'GET IT NOW', exact: false, first: true } },
  'kings_welcome_pack_bonus_code': { selectorType: 'role', selector: { role: 'button', name: 'GET IT NOW', exact: false, first: true } },
  'aviator_welcome_pack': { selectorType: 'role', selector: { role: 'button', name: 'Sign In', exact: true } },
  'aviator_welcome_pack_mindep20': { selectorType: 'role', selector: { role: 'button', name: 'Sign In', exact: true } },
  'wolfy_welcome_pack': { selectorType: 'role', selector: { role: 'button', name: 'PLAY NOW', exact: true } },
  'wolfy_welcome_pack_mindep30': { selectorType: 'role', selector: { role: 'button', name: 'PLAY NOW', exact: true } },
  'wheel_of_fortune': { selectorType: 'locator', selector: { locator: 'section', hasText: 'SPIN NOW 01 register To', role: 'button' } },
  'kings_land': { selectorType: 'locator', selector: { locator: 'section', hasText: 'WELCOME PACK €/$ 2500 + 250', role: 'button' } },
  'kings_no_dep': { selectorType: 'role', selector: { role: 'button', name: 'GET IT NOW', exact: false, first: true } },
  'kings_one_dollar_dep': { selectorType: 'role', selector: { role: 'button', name: 'GET IT NOW', exact: true } },
  'plinko_welcome_pack': { selectorType: 'role', selector: { role: 'button', name: 'Sign In', exact: true } },
  'askgamblers_50_free_spins': { selectorType: 'locator', selector: { locator: 'section', hasText: 'Vote for Us! Win 50 Extra', role: 'button' } },
  'kings_gun': { selectorType: 'role', selector: { role: 'button', name: 'shoot now', exact: true } },
  'book_of_king_billy': { selectorType: 'role', selector: { role: 'textbox', name: 'E-mail', exact: true } },
  'las_vegas_lights': { selectorType: 'role', selector: { role: 'button', name: 'GET BONUS', exact: false, first: true } },
  'casinoguru': { selectorType: 'locator', selector: { locator: 'main', role: 'button', name: 'Get it now', exact: true } },
  'kraken': { selectorType: 'locator', selector: { locator: 'main', role: 'button', name: 'Get it now', exact: false } },
  'kraken_guru': { selectorType: 'locator', selector: { locator: 'main', role: 'button', name: 'Get it now', exact: false } },
  'ndb': { selectorType: 'locator', selector: { locator: 'div', hasText: /^Get it now Bonus T&C's$/, role: 'button' } },
  'ndb_100': { selectorType: 'locator', selector: { locator: 'main', role: 'button', name: 'Get it now', exact: false } },
  'ndb_code': { selectorType: 'locator', selector: { locator: 'main', role: 'button', name: 'Get it now', exact: false } },
  'ndbKing': { selectorType: 'locator', selector: { locator: 'main', role: 'button', name: 'Get it now', exact: false } },
  'ndbKing_code': { selectorType: 'locator', selector: { locator: 'main', role: 'button', name: 'Get it now', exact: false } },
  'WelcomeCrypto': { selectorType: 'role', selector: { role: 'textbox', name: 'E-mail', exact: true } },
  'retargeting_20fs': { selectorType: 'role', selector: { role: 'textbox', name: 'E-mail', exact: true } },
  'welcome_250fs_elvis': { selectorType: 'role', selector: { role: 'button', name: 'GET IT NOW', exact: false, first: true } },
  'kings_welcome_pack_151': { selectorType: 'role', selector: { role: 'button', name: 'GET IT NOW', exact: false, first: true } },
  'christmas_welcome': { selectorType: 'locator', selector: { locator: 'section', hasText: 'Welcome Pack €/$ 2500 + 250', role: 'button' } },
  'kings_no_dep_100': { selectorType: 'role', selector: { role: 'button', name: 'GET IT NOW', exact: false, first: true } },
  'kings_no_dep_151': { selectorType: 'role', selector: { role: 'button', name: 'GET IT NOW', exact: false, first: true } },
  'kings_no_dep_151_open': { selectorType: 'role', selector: { role: 'button', name: 'Sign In', exact: true } },
  'welcome_chicken_road': { selectorType: 'locator', selector: { locator: 'section', hasText: 'Welcome Pack €/$2500 +250', role: 'button' } },
  'push_app': { selectorType: 'role', selector: { role: 'button', name: 'Sign In', exact: true } },
  'JS Welcome': { selectorType: 'role', selector: { role: 'button', name: 'GET IT NOW', exact: false, first: true } },
};
